site_name: SocialRadar LocationKit
pages:
  - Home: index.md
  - iOS:
    - 'Quickstart': ios/getting-started.md
    - 'Usage': ios/using-locationkit.md
    - 'Object Model': ios/object-model.md
    - 'API Reference': ios/api-reference.md
  - Android:
    - 'Quickstart': android/index.md
  - HTTP:
    - 'Quickstart': no-such-page.md
  - About: about.md
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
