site_name: SocialRadar LocationKit
pages:
  - Home: index.md
  - iOS:
    - 'Quickstart': ios/getting-started.md
    - 'Usage': ios/using-locationkit.md
    - 'Object Model': ios/object-model.md
    - 'API Reference': ios/api-reference.md
    - 'Change Log': ios/changelog.md
    - 'Sample App': ios/sample-app.md
  - Android:
    - 'Quickstart': android/index.md
  - HTTP:
    - 'Quickstart': http/index.md
  - Support: support.md
theme: readthedocs
repo_url: https://github.com/socialradar/locationkit-docs
markdown_extensions:
  - toc:
      permalink: True
