site_name: SocialRadar LocationKit
pages:
  - General: index.md
  - iOS:
    - 'Getting Started': ios/getting-started.md
    - 'Using LocationKit': ios/using-locationkit.md
  - Android:
    - 'General': android/index.md
  - Downloads: downloads/index.md
  - About: about.md
theme: readthedocs
